### ISSUE TITLE
What html source to use?

### ISSUE THREAD

**Issue by RealXuChe** [aplqo/cppreference-pdf#1]
I've tried to use an HTML archive from [here](https://github.com/PeterFeicht/cppreference-doc), I passed the `index.html` to the program, but it doesn't work with that archive.

I got an error message that says: "filesystem error: recursive directory iterator cannot open directory: No such file or directory [/cppref/cppreference-doc-20220201/reference/en.cppreference.com/index]".
and the stack trace is as follows:
```
#6  0x00007ffff7ca5ecd in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))
     (obj=<optimized out>, tinfo=0x7ffff7e2f818 <typeinfo for std::filesystem::__cxx11::filesystem_error>, dest=0x7ffff7d88060 <std::filesystem::__cxx11::filesystem_error::~filesystem_error()>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007ffff7c9d5ea in std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)
    (this=0x7fffffffdd90, p=filesystem::path "/cppref/cppreference-doc-20220201/reference/en.cppreference.com/index" = {...}, options=<optimized out>, ecptr=<optimized out>)
    at /usr/src/debug/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/new_allocator.h:90
#8  0x000055555555a71a in std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&)
    (this=0x7fffffffdd90, __p=filesystem::path "/cppref/cppreference-doc-20220201/reference/en.cppreference.com/index" = {...}) at /usr/include/c++/12.1.0/bits/fs_dir.h:474
#9  0x0000555555559e66 in doc::filelist::filelist(std::filesystem::__cxx11::path const&)
    (this=0x7fffffffdea0, p=filesystem::path "/cppref/cppreference-doc-20220201/reference/en.cppreference.com/index.html" = {...})
    at /cppreference-pdf/src/filelist.cpp:31
#10 0x0000555555558c3a in main(int, char**) (argc=3, argv=0x7fffffffe158) at /cppreference-pdf/src/main.cpp:51
```
I wonder what HTML files should I use?

**Comment by saxbophone** [comment]
Have you tried the _raw archives_ referenced on this page: https://en.cppreference.com/w/Cppreference:Archives ?

The missing filename seems to match that one...
